### ISSUE TITLE
commit completed but not seeing in branches..

### ISSUE THREAD

**Issue by rpasala** [githubteacher/fluffy-octo-guacamole#133]

**Comment by brianamarie** [comment]
@rpasala What is the name of your branch?

**Comment by rpasala** [comment]
ravi_bio

**Comment by rpasala** [comment]
\\psf\Home\Desktop\GitHub\fluffy-octo-guacamole [ravi-add-bio +1 ~0 -0 | +1 ~1 -
0 !]> git commit -m "Two Stage commit"
[ravi-add-bio 0891eb5] Two Stage commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 ravi_bio.md
\\psf\Home\Desktop\GitHub\fluffy-octo-guacamole [ravi-add-bio +1 ~1 -0 !]>

**Comment by brianamarie** [comment]
@rpasala You can check your branch locally with `git branch`. Is that what you're asking?

**Comment by rpasala** [comment]
how can we check the branch in server

**Comment by brianamarie** [comment]
@rpasala You can check by looking on the repository webpage, https://github.com/githubteacher/fluffy-octo-guacamole/ , and clicking "Branch: master" on the top left side. I'm not seeing your branch there now, which means you haven't pushed. To push, try: `git push -u origin <branch-name>`

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
