### ISSUE TITLE
Getting 403

### ISSUE THREAD

**Issue by dbarba4** [githubteacher/fluffy-octo-guacamole#139]
C:\Users\dbarba\Documents\GitHub\fluffy-octo-guacamole [dab-add-bio +1 ~0 -0 !]>
 git push -u origin dab-add-bio
Username for 'https://github.com': dbarba@allstate.com
Password for 'https://dbarba@allstate.com@github.com':
remote: Permission to githubteacher/fluffy-octo-guacamole.git denied to dbarba4.

fatal: unable to access 'https://github.com/githubteacher/fluffy-octo-guacamole.
git/': The requested URL returned error: 403

**Comment by crichID** [comment]
@dbarba4 I believe Theodore is working on the proxy issues now! Keep an eye out in Gitter for the solution!
