### ISSUE TITLE
git commit -a question 

### ISSUE THREAD

**Issue by rjhaylor** [githubteacher/fluffy-octo-guacamole#151]
Can you do a "git commit -a" to just one changed file or is it just for all? If its just for all how do you just commit and/or add just one changed file? I think I know the answer but please confirm. thanks

**Comment by brianamarie** [comment]
@rjhaylor To add just one changed file, include the name, like: ` git add <filename`. Is that what you were asking?

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄

**Comment by rjhaylor** [comment]
:+1:
