### ISSUE TITLE
merge failed

### ISSUE THREAD

**Issue by dpschreck** [githubteacher/fluffy-octo-guacamole#157]
after hitting confirm button, it says merge request failed.  Hit the try again button, checks to see if it's ready to merge, and allows me to try again.  But each one fails again.

**Comment by brianamarie** [comment]
@dpschreck If you're getting a bounce of merge attempt failed even though there are no requests, it's because of the high volume of attempts. This is case specific to this class, just keep trying. 😄

**Comment by dpschreck** [comment]
thanks.  it worked now.
