### ISSUE TITLE
merge request it failing

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#158]
I keep getting this message:

Merge attempt failed

We couldn’t merge this pull request. Reload the page before trying again.

**Comment by brianamarie** [comment]
@johnnyxyz1223  If you're getting a bounce of merge attempt failed even though there are no requests, it's because of the high volume of attempts. This is case specific to this class, just keep trying. 😄

**Comment by johnnyxyz1223** [comment]
got it. It worked after the 4th or 5th try. Thx

**Comment by brianamarie** [comment]
Great! 🎉
