### ISSUE TITLE
Failed merge without conflict

### ISSUE THREAD

**Issue by sadhu89** [githubteacher/fluffy-octo-guacamole#160]
![screenshot from 2016-05-11 13 33 09](https://cloud.githubusercontent.com/assets/5819854/15192029/fed236f4-177c-11e6-9548-29c4adaf26b5.png)

**Comment by brianamarie** [comment]
@sadhu89  If you're getting a bounce of merge attempt failed even though there are no conflicts, it's because of the high volume of attempts. This is case specific to this class, just keep trying. 😄
