### ISSUE TITLE
how can we use the Github for Salesforce

### ISSUE THREAD

**Issue by rpasala** [githubteacher/fluffy-octo-guacamole#162]

**Comment by brianamarie** [comment]
@rpasala I'm not sure I understand your question. Can you clarify what you mean?

**Comment by rpasala** [comment]
we want to user Github for our Salesforce application.. We have different environments, Dev, QA and Prod.  how can we use github for our migrations and version control

**Comment by crichID** [comment]
@rpasala we often get this question about versioning your Salesforce code with GitHub. There are a few options. One is to use their Metadata API. This blog post also has some helpful information: https://www.pagerduty.com/blog/easy-salesforce-deployments-slack-github/. I have also seen a few open source projects that handle the deployment!

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
