### ISSUE TITLE
How configure git to delete automatically the local branch after delete the remote branch?

### ISSUE THREAD

**Issue by sadhu89** [githubteacher/fluffy-octo-guacamole#164]

**Comment by brianamarie** [comment]
@sadhu89 Let me know if this answers your question:

- Back at the command line, we need to pull down the changes from GitHub.com in the remote repository.
   - `git checkout master`
   - `git pull`
   - `git branch --merged`
   - `git branch -d <branch-name>`
   - `git fetch --prune`
- Configure your settings to do this by default by typing `git config --global fetch.prune true`

**Comment by sadhu89** [comment]
I would like to avoid executing git branch -d each time I delete a branch on github. Is not possible to make that automatically?

**Comment by brianamarie** [comment]
@sadhu89 That's a great question - I'm going to queue it up for Patrick to answer on the webinar. 😄

**Comment by brianamarie** [comment]
@sadhu89 Using `git config --global fetch.prune true` will help this happen as automatically as possible.

**Comment by brianamarie** [comment]
I'm going to close this issue now. If I didn't answer your question, please feel free to comment here again and I'll check it out later. 😄  See you in the webinar tomorrow!

**Comment by sadhu89** [comment]
@brianamarie Could you explain me what exactly makes `git config --global fetch.prune true` please?

**Comment by brianamarie** [comment]
@sadhu89 

>**fetch.prune**
>If true, fetch will automatically behave as if the --prune option was given on the command line. See also remote.<name>.prune. 

- [_From Git-scm.com_](https://git-scm.com/docs/git-config)

This means that every time you fetch (which is included in a pull), if the branch has been deleted on the remote repository, it will automatically 'prune' it from the local repository also. More information is available at the [Git-Scm.com](https://git-scm.com/docs/git-config) site.
