### ISSUE TITLE
is there a glossary of flags?

### ISSUE THREAD

**Issue by eitah** [githubteacher/fluffy-octo-guacamole#166]

**Comment by brianamarie** [comment]
@eitah Great question. Yes, there is, here: https://git-scm.com/docs/git-log

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
