### ISSUE TITLE
The alias command didn't work

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#167]
It looks like the alias command name was missing. Maybe Patrick already had it defined and that's why it worked for him?

**Comment by johnnyxyz1223** [comment]
This is what I did:
C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [master ≡]> git config --global alias.lg "log --oneline --graph --decorate"
C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [master ↓]> lg -5
lg : The term 'lg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lg -5
+ ~~
    + CategoryInfo          : ObjectNotFound: (lg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by crichID** [comment]
@johnnyxyz1223 you still have to use git in front of the lg command. So the command would be `git lg`

**Comment by johnnyxyz1223** [comment]
Thanks. It hung my power shell. (I think).

why did the alias command change my prompt from blue to red with a downward pointing arrow?

**Comment by johnnyxyz1223** [comment]
C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [master ≡]> git config --global alias.lg "log --oneline --graph --de
corate"
C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [master ↓]>

**Comment by brianamarie** [comment]
@johnnyxyz1223 Interesting question. I don't have an immediate answer for you, sometimes differences in command lines can be pretty large. Do you mind posting a screenshot?

**Comment by johnnyxyz1223** [comment]
luv 2. let me fiddle w/the controls 2 figure out how

**Comment by johnnyxyz1223** [comment]
![cmd_prmt_chng](https://cloud.githubusercontent.com/assets/18402093/15193619/9cb1db68-1773-11e6-9053-927a6da37fa9.png)
Did that work?

**Comment by johnnyxyz1223** [comment]
I guess so

**Comment by brianamarie** [comment]
@johnnyxyz1223 Thank you for posting a screen shot!

What happens if you type `clear` and try `git lg -5` again? Does the red arrow persist? If so, what about `git status`?

**Comment by johnnyxyz1223** [comment]
![red_cmd_prmpt](https://cloud.githubusercontent.com/assets/18402093/15194355/5d6bdbee-1777-11e6-87b3-f468b0cd5deb.png)
even after that it remains red. The red arrow is telling me something. I just don't know what it is.

**Comment by brianamarie** [comment]
@johnnyxyz1223 Your guess is as good as mine, I'm sorry I can't be of more help! My only last suggestion is to try `git pull` to see if it's trying to tell you that your version of the repository isn't updated. Other than that, I'm out of ideas! I would research online based on your terminal settings.

**Comment by johnnyxyz1223** [comment]
@brianamarie yep. Good call. git pull cleared it.

**Comment by brianamarie** [comment]
[](url)
