### ISSUE TITLE
unable to delete folder

### ISSUE THREAD

**Issue by rpasala** [githubteacher/fluffy-octo-guacamole#178]
\\psf\Home\Desktop\GitHub\fluffy-octo-guacamole [ravi-add-bio ≡ +1 ~1 -0 !]> rm
-rf fluffy-octo-guacamole
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:7
+ rm -rf <<<<  fluffy-octo-guacamole
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBin
   dingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
   ands.RemoveItemCommand

**Comment by brianamarie** [comment]
@rpasala Are you trying to delete the entire repository?

**Comment by brianamarie** [comment]
@rpasala If so, I suggest deleting the directory through explorer or finder.

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
