### ISSUE TITLE
git checkout -b update-cam-bio is not working.  Fatal error: Not a git repository.

### ISSUE THREAD

**Issue by cmirrop** [githubteacher/fluffy-octo-guacamole#179]

**Comment by brianamarie** [comment]
@cmirrop Have you CD'd into your newly cloned repository?

**Comment by cmirrop** [comment]
that works now.  thanks.

**Comment by brianamarie** [comment]
Great! I'm going to close this issue. Please feel free to comment here again or open an new issue if you continue to have questions. :smile:

**Comment by cmirrop** [comment]
what do I do to catch up from here - I can't see his commands

**Comment by brianamarie** [comment]
- See all of the bios: `ls bios/`
- Create a new branch and checkout to it: `git checkout -b new-unique-branch-name`
- Make changes locally to your own file in your favorite text editor. Save your changes and exit your text editor.
- Commit your changes:
  - `git add <filename>`
  - `git commit -m "enter short descriptive commit message"`

**Comment by cmirrop** [comment]
I just finished the above.  But I am lost as to where he is now....  what are the next steps now??

**Comment by brianamarie** [comment]
@cmirrop Mostly review. For now, just make one more change, add and commit using the steps above. You'll be with us then. 😄
