### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by ppeters2016** [githubteacher/fluffy-octo-guacamole#18]
SSL cert problem: self-signed cert in the chain

**Comment by DLimsom** [comment]
same here.

**Comment by brianamarie** [comment]
@ppeters2016 @DLimsom Are you using the Allstate proxy, or do you have another proxy set up that you know of?  If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
