### ISSUE TITLE
How can we use github for Oracle Bigmachines

### ISSUE THREAD

**Issue by rpasala** [githubteacher/fluffy-octo-guacamole#183]
We are using Oracle Bigmachines in our project..we dont have any version control.. can we use Github?

**Comment by brianamarie** [comment]
@rpasala I'm looking into an answer for you 😄

**Comment by brianamarie** [comment]
@rpasala Great question! While I don’t know a ton about Oracle BigMachines I haven’t encountered many setups that did not permit GitHub use. We’d love to chat some more about your use case and see how GitHub can help.

**Comment by brianamarie** [comment]
@rpasala If you'd like, please email services@github.com with your question and we will make sure to get you the best answer for your specific use case.

**Comment by brianamarie** [comment]
I'm going to close this issue. As I said before, please feel free to email services@github.com for a more in-depth and personalized answer to your fantastic question. 👍
