### ISSUE TITLE
can't push branch up

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#185]
tried this:
C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [update-jds-bio +0 ~1 -0 ~]> git push -u update-jds-bio
fatal: The current branch update-jds-bio has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream update-jds-bio update-jds-bio

C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [update-jds-bio +0 ~1 -0 ~]> git push --set-upstream update-jds-bio
update-jds-bio
fatal: 'update-jds-bio' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by brianamarie** [comment]
@johnnyxyz1223 Uh oh. Are these the same errors you were seeing yesterday [here](https://github.com/githubteacher/fluffy-octo-guacamole/issues/53)?

Try `git push -u origin update-jds-bio`

**Comment by johnnyxyz1223** [comment]
@brianamarie worked

**Comment by brianamarie** [comment]
@johnnyxyz1223 Fantastic! I am going to close this issue, but you know to feel free to comment again if need be. 😄
