### ISSUE TITLE
Not able to clone

### ISSUE THREAD

**Issue by etan12345** [githubteacher/fluffy-octo-guacamole#20]
$ git clone https://github.com/githubteacher/fluffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
fatal: unable to access 'https://github.com/githubteacher/fluffy-octo-guacamole.git/': The requested URL returned error: 503

**Comment by drew21** [comment]
I am in the same state

**Comment by halfaro1** [comment]
@etan12345 and @drew21 are you behind a company firewall by any chance? A number of other folks are having the same issue. Typically you can set a proxy using `git config` but you'd have to know the proxy server.

**Comment by drew21** [comment]
i dont know that could be

**Comment by halfaro1** [comment]
@drew21 if you are and you happen to know the proxy server you can let git know using `git config --global http.proxy <your-proxy>`

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work 😄
