### ISSUE TITLE
can't clone into fluffy-ocoto-guacamole

### ISSUE THREAD

**Issue by ifemi99** [githubteacher/fluffy-octo-guacamole#21]
h:\>git clone git@github.com:githubteacher/fluffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by brianamarie** [comment]
@ifemi99 Are you using the Allstate proxy, or do you have another proxy set up that you know of?

**Comment by brianamarie** [comment]
@ifemi99 If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work 😄

**Comment by ifemi99** [comment]
I'm using Allstate Proxy and I'll contact Theodore
