### ISSUE TITLE
Can't clone

### ISSUE THREAD

**Issue by wstcstrd9r** [githubteacher/fluffy-octo-guacamole#22]
C:\Users\U453949\Desktop\GitHub> git clone git@github.com:githubteacher\fluffy.o
cto-guacomole.git
Cloning into 'fluffy.octo-guacomole'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by somalsood** [comment]
same for me

**Comment by butlerx** [comment]
use http not ssh

**Comment by somalsood** [comment]
git clone https://github.com/githubteacher/fluffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
fatal: unable to access 'https://github.com/githubteacher/fluffy-octo-guacamole.git/': The requested URL returned error: 503

**Comment by wstcstrd9r** [comment]
I tried both

**Comment by halfaro1** [comment]
👋 hi folks! First, try cloning with HTTPS. If that doesn't work an you happen to be behind a company firewall, you can set a proxy server using `git config --global http.proxy <your-proxy>`

**Comment by somalsood** [comment]
Thanks, it worked for me

**Comment by halfaro1** [comment]
👍 I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work 😄
