### ISSUE TITLE
I am unable to Clone   

### ISSUE THREAD

**Issue by brendazim** [githubteacher/fluffy-octo-guacamole#25]

**Comment by brendazim** [comment]
used https: and got the access failed      
then try the SSL     and got the repository does not exists

**Comment by brianamarie** [comment]
@brendazim Are you using the Allstate proxy, or do you have another proxy set up that you know of?

**Comment by brendazim** [comment]
I am using Allstate

**Comment by brianamarie** [comment]
@brendazim    If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work 😄
