### ISSUE TITLE
merge conflict preventing pull request

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#256]
having trouble getting merge request resolved

**Comment by brianamarie** [comment]
@johnnyxyz1223 Can you give me a little more information? Is it appearing on GitHub.com for your pull request, or have you tried to fix the merge conflict via command line?

**Comment by johnnyxyz1223** [comment]
got it. Just having troubles stuck with only laptop screen. No 2nd monitor for bigger screen real estate. I had to use the command lines to get it to work

**Comment by brianamarie** [comment]
@johnnyxyz1223 Ah, I see. Thanks for letting me know! If you're using the command like to get it to work, sounds like you're a pro! 🎉

**Comment by johnnyxyz1223** [comment]
@brianamarie thanks.
