### ISSUE TITLE
trying to use atom

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#259]
I used the command Patrick provided yesterday

git config --global core.editor "atom --wait"

But if I try atom <new_file> in the command shell I get this message:

C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [master ≡]> atom
atom : The term 'atom' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ atom
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (atom:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

It's not finding atom

**Comment by brianamarie** [comment]
@johnnyxyz1223 I see. There are some more configurations needed in atom to get this to function. For now, are you able to open the file by first opening atom, then finding the file in the correct branch?

**Comment by johnnyxyz1223** [comment]
@brianamarie yeah. It just feels a little slow doing it that way

**Comment by brianamarie** [comment]
@johnnyxyz1223 I'm sorry. I'm going to find you a resource to get everything set up so you can open with `atom <file>`. 👍

**Comment by brianamarie** [comment]
@johnnyxyz1223 Based on [this help doc](https://help.github.com/articles/associating-text-editors-with-git/), it seems you're doing everything correctly. My suggestion would be checking the version of atom and maybe updating.

**Comment by johnnyxyz1223** [comment]
@brianamarie I think this is the version I have: C:\Users\seiberli\AppData\Local\atom\app-1.7.3?

**Comment by brianamarie** [comment]
@johnnyxyz1223 Ah, It appears you need to set a path for atom. More info on that if you aren't familiar [here](http://www.computerhope.com/issues/ch000549.htm).

**Comment by halfaro1** [comment]
@johnnyxyz1223 this may help
![path-atom](https://cloud.githubusercontent.com/assets/16547949/15224512/d91a665e-1847-11e6-82ac-be7d3792c3e2.gif)

**Comment by johnnyxyz1223** [comment]
added path to atom: C:\Users\seiberli\AppData\Local\atom\bin in both the TEMP and PATH env variable. Tested and it's still not working from the command line of the power shell. Closed power shell and opened a new one, but still doesn't work. 

C:\Users\seiberli\work\GitHub\fluffy-octo-guacamole [master ≡]> atom
atom : The term 'atom' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ atom
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (atom:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by johnnyxyz1223** [comment]
halfaro1's vid recording is good but moves too fast to get detail of which env var is being modified

**Comment by halfaro1** [comment]
@johnnyxyz1223 log out of your user account and log back in for it to take effect. You can also click on the gif and watch it a couple of times -- it repeats

**Comment by johnnyxyz1223** [comment]
@brianamarie Logging off is a major deal. But it works now. no more errors invoking atom from the command line. Thanks.

**Comment by johnnyxyz1223** [comment]
@halfaro1 it's working after a logout and login

**Comment by johnnyxyz1223** [comment]
Thank you both

**Comment by brianamarie** [comment]
@johnnyxyz1223 Fantastic! 🎉  I'm so glad it's working. I'm going to close this issue now. 😄
