### ISSUE TITLE
I am unable to Clone

### ISSUE THREAD

**Issue by ebrodersen** [githubteacher/fluffy-octo-guacamole#26]

**Comment by brianamarie** [comment]
@ebrodersen Are you using the Allstate proxy, or do you have another proxy set up that you know of?

**Comment by ebrodersen** [comment]
Allstate

**Comment by brianamarie** [comment]
If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by halfaro1** [comment]
I'm closing this issue to keep track of answered questions but feel free to reopen if you have a follow up or that still doesn't work 😄
