### ISSUE TITLE
Could you go little bit slow?

### ISSUE THREAD

**Issue by standardfin** [githubteacher/fluffy-octo-guacamole#27]
Could you go little bit slow?

**Comment by brianamarie** [comment]
@standardfin I will let Patrick know of your request. 😄  Be sure to join us in the gitter room so you can tell us there, too: https://gitter.im/githubteacher/fluffy-octo-guacamole

**Comment by halfaro1** [comment]
I'm closing this issue to keep track of answered questions but feel free to reopen if you have a follow up or that still doesn't work 😄
