### ISSUE TITLE
GitHub line editor is not showing up in my program list - using Windows Power Shell for now.  How do I fix this?

### ISSUE THREAD

**Issue by cmirrop** [githubteacher/fluffy-octo-guacamole#29]

**Comment by brianamarie** [comment]
@cmirrop Windows Power Shell should work as long as you have Git and the dependencies installed. 😄 Let us know in gitter if you have any issues: https://gitter.im/githubteacher/fluffy-octo-guacamole

**Comment by brianamarie** [comment]
I am going to close this issue, please feel free to re-open it and `@` mention me if you need more help and aren't finding it in Gitter. 😄
