### ISSUE TITLE
Can't clone.

### ISSUE THREAD

**Issue by lranasinghe** [githubteacher/fluffy-octo-guacamole#30]
I get the following exception:

$ git clone https://github.com/githubteacher/fluffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
fatal: unable to access 'https://github.com/githubteacher/fluffy-octo-guacamole.git/': Failed to connect to github.com port 443: Timed out

**Comment by jguntaka** [comment]
Same here

**Comment by halfaro1** [comment]
@lranasinghe and @jguntaka do you happen to be with Allstate?

**Comment by brianamarie** [comment]
@lranasinghe @jguntaka   If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
