### ISSUE TITLE
what is the +1 ~0 -0 !

### ISSUE THREAD

**Issue by rpasala** [githubteacher/fluffy-octo-guacamole#32]
\psf\Home\Desktop\GitHub\fluffy-octo-guacamole [ravi-add-bio]> touch ravi_bio.md

\psf\Home\Desktop\GitHub\fluffy-octo-guacamole [ravi-add-bio +1 ~0 -0 !]>

**Comment by githubteacher** [comment]
@rpasala that is just your command prompt showing you have changes in your working tree!

**Comment by halfaro1** [comment]
I'm closing this issue to keep track of answered questions but feel free to reopen if you have a follow up or that still doesn't work 😄
