### ISSUE TITLE
unable to clone the repo

### ISSUE THREAD

**Issue by pavanivatury** [githubteacher/fluffy-octo-guacamole#33]
C:\>git clone git@github.com:githubteacher/fluffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
ssh: connect to host github.com port 22: Bad file number
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by halfaro1** [comment]
@pavanivatury try cloning with HTTPS: `git clone https://github.com/githubteacher/fluffy-octo-guacamole.git`

**Comment by pavanivatury** [comment]
no luck
C:\>git clone https://github.com/githubteacher/fluffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
fatal: unable to access 'https://github.com/githubteacher/fluffy-octo-guacamole.
git/': The requested URL returned error: 503

**Comment by halfaro1** [comment]
Are any of you with Allstate by chance?

**Comment by brianamarie** [comment]
@pavanivatury   If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by brianamarie** [comment]
@pavanivatury I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
