### ISSUE TITLE
Cannot do touch

### ISSUE THREAD

**Issue by westlake91361** [githubteacher/fluffy-octo-guacamole#34]
after checkout and did git branch to confirm i'm on the branch, did "touch xxxx.md" but got: 'touch' is not recognized as an internal or external command, operable program or batch file

**Comment by halfaro1** [comment]
@westlake91361 if you're on a Windows machine, launch Git Bash in your programs and that will emulate a Unix environment which will allow you to use the `touch` command

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work.
