### ISSUE TITLE
How do I get that chat feature?  what is it called?

### ISSUE THREAD

**Issue by mscerutti** [githubteacher/fluffy-octo-guacamole#36]

**Comment by halfaro1** [comment]
It's called Gitter and you can get to it on [this link](https://gitter.im/githubteacher/fluffy-octo-guacamole?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). If it works for you please close this issue, otherwise feel free to keep asking questions here :)

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work.
