### ISSUE TITLE
cant clone

### ISSUE THREAD

**Issue by Testwithgit** [githubteacher/fluffy-octo-guacamole#37]
getting error connection timed out

**Comment by brianamarie** [comment]
Are you using the Allstate proxy, or do you have another proxy set up that you know of?  If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by brianamarie** [comment]
@Testwithgit See my comment above for help 😄

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
