### ISSUE TITLE
after typing the touch command my command prompt changed to something weird

### ISSUE THREAD

**Issue by johnnyxyz1223** [githubteacher/fluffy-octo-guacamole#40]
[jds-add-bio +1 ~0 -0 !]

The "+1 ~0 -0!" started just after the touch command. I guess I need a little nudge with changing the command prompt in git command window?

**Comment by githubteacher** [comment]
@johnnyxyz1223 that is just your command prompt showing you have changes in your working tree!

**Comment by johnnyxyz1223** [comment]
cool. Thanks.
