### ISSUE TITLE
Cannot Clone.

### ISSUE THREAD

**Issue by JKGHAcc0unt** [githubteacher/fluffy-octo-guacamole#43]
! am getting -  fatal: unable to access 'https://..." : SSL certificate problem.

**Comment by halfaro1** [comment]
@JKGHAcc0unt are you being a company firewall by any chance?

**Comment by JKGHAcc0unt** [comment]
yes

**Comment by halfaro1** [comment]
@JKGHAcc0unt Allstate?

**Comment by JKGHAcc0unt** [comment]
yes

**Comment by halfaro1** [comment]
@JKGHAcc0unt Please contact Theodore Salvo via Lync at `tsalw` he should be able to help you set the right proxy server.
I'm closing this issue to keep track of answered questions but feel free to reopen if you have a follow up or that still doesn't work 😄

**Comment by JKGHAcc0unt** [comment]
ok thanks
