### ISSUE TITLE
unable to add label to my issue

### ISSUE THREAD

**Issue by do-not-forsake-me** [githubteacher/fluffy-octo-guacamole#45]
I do not see the option to label my issue as demontrated

**Comment by brianamarie** [comment]
@do-not-forsake-me It looks like you haven't commented on the issue to be added as a collaborator. Try commenting here, then give us a moment to run the script that will add you: https://github.com/githubteacher/fluffy-octo-guacamole/issues/3

**Comment by do-not-forsake-me** [comment]
<comment>

**Comment by brianamarie** [comment]
@do-not-forsake-me You should be a collaborator now. ✨ 
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
