### ISSUE TITLE
Problem with touch command

### ISSUE THREAD

**Issue by divyam01986** [githubteacher/fluffy-octo-guacamole#46]
When I type touch myBio.md, I get the following error message:

touch : The term 'touch' is not recognized as the name of a cmdlet, function, script file, or operable
the spelling of the name, or if a path was included, verify that the path is correct and try again.

How can I help Git Shell recognize this command?

**Comment by halfaro1** [comment]
@divyam01986 if you're on a windows machine you can use Git Bash to use commands like those that work on Unix environments. I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work.

**Comment by divyam01986** [comment]
Thanks
