### ISSUE TITLE
cannot clone 

### ISSUE THREAD

**Issue by dbarba4** [githubteacher/fluffy-octo-guacamole#47]
C:\Users\dbarba\Documents\GitHub> git clone git@github.com:githubteacher/fluffy-
octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unlink of file 'fluffy-octo-guacamole/.git/hooks/pre-applypatch.sample' failed.
Should I try again? (y/n) y
Unlink of file 'fluffy-octo-guacamole/.git/hooks/pre-commit.sample' failed. Shou
ld I try again? (y/n) y
Unlink of file 'fluffy-octo-guacamole/.git/hooks/pre-push.sample' failed. Should
 I try again? (y/n) n
Unlink of file 'fluffy-octo-guacamole/.git/hooks/prepare-commit-msg.sample' fail
ed. Should I try again? (y/n) n
C:\Users\dbarba\Documents\GitHub> git clone https://github.com/githubteacher/flu
ffy-octo-guacamole.git
fatal: destination path 'fluffy-octo-guacamole' already exists and is not an emp
ty directory.

**Comment by githubteacher** [comment]
@dbarba4 would you happen to be at Allstate?

**Comment by dbarba4** [comment]
yes

**Comment by brianamarie** [comment]
@dbarba4  If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work 😄

**Comment by eitah** [comment]
git config --global http.proxy http://webproxy.igslb.allstate.com:8080
git config --global http.sslVerify false

**Comment by dbarba4** [comment]
Thanks got that to work but git branch still not working
C:\Users\dbarba\Documents\GitHub> git branch
fatal: Not a git repository (or any of the parent directories): .git

**Comment by dbarba4** [comment]
Previous git command
C:\Users\dbarba\Documents\GitHub> git clone https://github.com/githubteacher/flu
ffy-octo-guacamole.git
Cloning into 'fluffy-octo-guacamole'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12 (delta 3), reused 10 (delta 1), pack-reused 0
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
C:\Users\dbarba\Documents\GitHub> git branch
fatal: Not a git repository (or any of the parent directories): .git

**Comment by brianamarie** [comment]
@dbarba4 It sounds like you aren't in the current repository that you cloned. Try: `fluffy-octo-guacamole`, then the branch command.
