### ISSUE TITLE
Aborting commit due to empty commit message

### ISSUE THREAD

**Issue by rpasala** [githubteacher/fluffy-octo-guacamole#49]
notepad not saving my text

**Comment by halfaro1** [comment]
@rpasala did you set notepad as your commit message? you can always bypass the text editor by using this command `commit -m "your commit message here"`

**Comment by rpasala** [comment]
\\psf\Home\Desktop\GitHub\fluffy-octo-guacamole [ravi-add-bio +1 ~0 -0 | +1 ~1 -
0 !]> commit -m "Two Stage commit"
The term 'commit' is not recognized as the name of a cmdlet, function, script f
ile, or operable program. Check the spelling of the name, or if a path was incl
uded, verify that the path is correct and try again.
At line:1 char:7
+ commit <<<<  -m "Two Stage commit"
    + CategoryInfo          : ObjectNotFound: (commit:String) [], CommandNotFo
   undException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by brianamarie** [comment]
@rpasala Try `git commit -m "your commit message here"`. It looks like you tried it without "git" at the front.

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
