### ISSUE TITLE
Error while Push

### ISSUE THREAD

**Issue by somalsood** [githubteacher/fluffy-octo-guacamole#51]
The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by brianamarie** [comment]
@somalsood  I'm sorry these hiccups are happening. Unfortunately, as far as we know these issues are with your network proxy and not with Git or GitHub. If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by somalsood** [comment]
sure

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully will be working well soon. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
