### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by do-not-forsake-me** [githubteacher/fluffy-octo-guacamole#52]
$ git push -u origin learn-git-01
Total 0 (delta 0), reused 0 (delta 0)
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503 Service Unavailable
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by brianamarie** [comment]
@do-not-forsake-me I'm sorry these hiccups are happening. Unfortunately, as far as we know these issues are with your network proxy and not with Git or GitHub. If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by brianamarie** [comment]
@do-not-forsake-me I'm going to close this issue, hopefully all is working well. Please feel free to comment here again if you are having issues. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄
