### ISSUE TITLE
GIt PUSH doesn't work 

### ISSUE THREAD

**Issue by TinmanAllstate** [githubteacher/fluffy-octo-guacamole#56]

**Comment by TinmanAllstate** [comment]
C:\Users\ypatf\Documents\GitHub\fluffy-octo-guacamole [ypatf-add-bio]> git push
-u origin ypatf-add-bio
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 294 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503 Servic
e Unavailable
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
C:\Users\ypatf\Documents\GitHub\fluffy-octo-guacamole [ypatf-add-bio]>

**Comment by brianamarie** [comment]
@TinmanAllstate I've seen this in another issue as well. I'm sorry these hiccups are happening. Unfortunately, as far as we know these issues are with your network proxy and not with Git or GitHub. If you are using Allstate, contact Theodore Salvo via Lync at `tsalw`.

**Comment by brianamarie** [comment]
I'm going to close this issue, hopefully all will be working well soon. Please feel free to comment here again if you are having issues that I can help you with. Or, let us know in gitter: https://gitter.im/githubteacher/fluffy-octo-guacamole 😄

**Comment by bbusche** [comment]
This is a cross reference #30
